// Sources de données QGISIA+
// Catalogue nettoyé (audit 2026-04-26) — uniquement sources vérifiées fonctionnelles
// + connecteurs Sprint 4 (IGN LiDAR, Géorisques, INPN, GPU, Sandre)
// Les APIs REST pures (Hub'Eau, GBIF, DVF) nécessitent un connecteur backend dédié — voir Sprint 4 phase complète

import { CatalogItem } from "./catalog";

// ═══════════════════════════════════════════════════════════════════════════════
// FONDS DE CARTE (raster XYZ/WMTS)
// ═══════════════════════════════════════════════════════════════════════════════

export const BASEMAP_SOURCES: CatalogItem[] = [
  {
    id: "osm-standard",
    name: "OpenStreetMap Standard",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    description: "Fond OSM standard",
    zMin: 0,
    zMax: 19,
    attribution: "OpenStreetMap contributors",
    reliable: true,
  },
  {
    id: "osm-hot",
    name: "OSM HOT (Humanitarian)",
    provider: "OSM France",
    serviceType: "XYZ",
    url: "https://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
    description: "OSM style humanitaire",
    zMin: 0,
    zMax: 19,
    attribution: "OpenStreetMap contributors",
    reliable: true,
  },
  {
    id: "carto-dark",
    name: "Carto Dark Matter",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png",
    description: "Fond sombre pour visualisation analytique",
    zMin: 0,
    zMax: 20,
    reliable: true,
    attribution: "OpenStreetMap, CARTO",
  },
  {
    id: "carto-positron",
    name: "Carto Positron",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
    description: "Fond clair minimaliste",
    zMin: 0,
    zMax: 20,
    reliable: true,
    attribution: "OpenStreetMap, CARTO",
  },
  {
    id: "carto-voyager",
    name: "Carto Voyager",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png",
    description: "Style navigation épuré",
    zMin: 0,
    zMax: 20,
    reliable: true,
    attribution: "OpenStreetMap, CARTO",
  },
  {
    id: "esri-world-imagery",
    name: "Esri World Imagery",
    provider: "Esri",
    serviceType: "XYZ",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    description: "Imagerie satellite mondiale haute résolution",
    zMin: 0,
    zMax: 19,
    attribution: "Esri, Maxar, Earthstar Geographics",
    reliable: true,
  },
  {
    id: "esri-street",
    name: "Esri World Street",
    provider: "Esri",
    serviceType: "XYZ",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
    description: "Rues du monde",
    zMin: 0,
    zMax: 19,
    attribution: "Esri",
    reliable: true,
  },
  {
    id: "esri-topo",
    name: "Esri World Topo",
    provider: "Esri",
    serviceType: "XYZ",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
    description: "Topographie mondiale",
    zMin: 0,
    zMax: 19,
    attribution: "Esri",
    reliable: true,
  },
  {
    id: "esri-shaded",
    name: "Esri Shaded Relief",
    provider: "Esri",
    serviceType: "XYZ",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}",
    description: "Relief ombré",
    zMin: 0,
    zMax: 13,
    attribution: "Esri",
    reliable: true,
  },
  {
    id: "esri-natgeo",
    name: "Esri National Geographic",
    provider: "Esri",
    serviceType: "XYZ",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}",
    description: "Carte style National Geographic",
    zMin: 0,
    zMax: 16,
    attribution: "Esri, National Geographic",
    reliable: true,
  },
  {
    id: "usgs-topo",
    name: "USGS Topo (US uniquement)",
    provider: "USGS",
    serviceType: "XYZ",
    url: "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}",
    description: "Carte topographique USGS",
    zMin: 0,
    zMax: 16,
    attribution: "USGS",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// TOPOGRAPHIE IGN (WMTS Géoplateforme — sans clé)
// ═══════════════════════════════════════════════════════════════════════════════

export const TOPOGRAPHIC_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "ign-planign",
    name: "Plan IGN V2",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Fond plan IGN V2 détaillé",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "ign-scan25",
    name: "SCAN 25® — Topo 1:25 000",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Carte topographique 1:25 000 IGN",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOUR",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "ign-scan-express-std",
    name: "SCAN Express Standard",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Carte topographique déclinée à toutes échelles",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "ign-scan-express-classique",
    name: "SCAN Express Classique",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Topo style classique 1:100k",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.CLASSIQUE",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "ign-cassini",
    name: "Carte de Cassini (XVIIIᵉ)",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Carte historique de Cassini (XVIIIᵉ siècle)",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.CASSINI",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "ign-etatmajor",
    name: "Carte État-Major (XIXᵉ)",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Carte État-Major 1:40 000 (XIXᵉ siècle)",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.ETATMAJOR40",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// IMAGERIE SATELLITE / ORTHO
// ═══════════════════════════════════════════════════════════════════════════════

export const SATELLITE_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "geopf-wmts-ortho",
    name: "Orthophotos IGN (WMTS)",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Photographies aériennes nationales 20cm",
    layerName: "ORTHOIMAGERY.ORTHOPHOTOS",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "geopf-wmts-ortho-irc",
    name: "Orthos Infrarouge (IRC)",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Orthophotos infrarouge couleur (végétation)",
    layerName: "ORTHOIMAGERY.ORTHOPHOTOS.IRC",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "geopf-wmts-ortho-historique",
    name: "Orthos historiques 1950-1965",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Photographies aériennes historiques",
    layerName: "ORTHOIMAGERY.ORTHOPHOTOS.1950-1965",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// LIDAR HD (Sprint 4 — IGN LiDAR)
// ═══════════════════════════════════════════════════════════════════════════════

export const LIDAR_SOURCES: CatalogItem[] = [
  {
    id: "ign-lidarhd-mnt",
    name: "LiDAR HD — MNT 1m",
    provider: "IGN Géoplateforme",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Modèle Numérique de Terrain LiDAR HD (résolution 1m)",
    layerName: "IGNF_LIDAR-HD_MNT_ELEVATION.ELEVATIONGRIDCOVERAGE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN LiDAR HD",
    reliable: true,
  },
  {
    id: "ign-lidarhd-mns",
    name: "LiDAR HD — MNS 1m",
    provider: "IGN Géoplateforme",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Modèle Numérique de Surface LiDAR HD (résolution 1m)",
    layerName: "IGNF_LIDAR-HD_MNS_ELEVATION.ELEVATIONGRIDCOVERAGE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN LiDAR HD",
    reliable: true,
  },
  {
    id: "ign-alti-rge",
    name: "RGE ALTI® — MNT 1m",
    provider: "IGN Géoplateforme",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Modèle Numérique de Terrain national 1m",
    layerName: "ELEVATION.ELEVATIONGRIDCOVERAGE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN RGE ALTI",
    reliable: true,
  },
  {
    id: "ign-alti-ombre",
    name: "RGE ALTI® — Ombrage",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Relief ombré issu du RGE ALTI",
    layerName: "ELEVATION.ELEVATIONGRIDCOVERAGE.SHADOW",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// LIMITES ADMINISTRATIVES (WFS IGN)
// ═══════════════════════════════════════════════════════════════════════════════

export const ADMINISTRATIVE_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-communes-wfs",
    name: "Communes",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Contours des communes françaises (ADMINEXPRESS)",
    layerName: "ADMINEXPRESS-COG-CARTO.LATEST:commune",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-departements-wfs",
    name: "Départements",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Contours des départements français",
    layerName: "ADMINEXPRESS-COG-CARTO.LATEST:departement",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-regions-wfs",
    name: "Régions",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Contours des régions françaises",
    layerName: "ADMINEXPRESS-COG-CARTO.LATEST:region",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-epci-wfs",
    name: "EPCI (Intercommunalités)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Établissements Publics de Coopération Intercommunale",
    layerName: "ADMINEXPRESS-COG-CARTO.LATEST:epci",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// BÂTI, ROUTES, ADRESSES (BD TOPO V3 — WFS IGN)
// ═══════════════════════════════════════════════════════════════════════════════

export const INFRASTRUCTURE_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-bati",
    name: "Bâtiments",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Emprise au sol des bâtiments (BD TOPO V3)",
    layerName: "BDTOPO_V3:batiment",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-adresse",
    name: "Adresses",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Adresses postales BAN (BD TOPO V3)",
    layerName: "BDTOPO_V3:adresse",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-routes",
    name: "Réseau routier",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Tronçons de route (BD TOPO V3)",
    layerName: "BDTOPO_V3:troncon_de_route",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-voies-ferrees",
    name: "Voies ferrées",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Tronçons ferroviaires (BD TOPO V3)",
    layerName: "BDTOPO_V3:troncon_de_voie_ferree",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// FORÊTS (BD FORÊT V2 — WFS IGN)
// ═══════════════════════════════════════════════════════════════════════════════

export const FORESTRY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-bdforet-formation",
    name: "BD Forêt — Formations végétales",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Formations végétales (BD Forêt V2)",
    layerName: "LANDCOVER.FORESTINVENTORY.V2:formation_vegetale",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN BD Forêt V2",
    reliable: true,
  },
  {
    id: "fr-bdforet-essence",
    name: "BD Forêt — Essences dominantes",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Essences forestières dominantes (BD Forêt V2)",
    layerName: "LANDCOVER.FORESTINVENTORY.V2:essence",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN BD Forêt V2",
    reliable: true,
  },
  {
    id: "fr-zone-vegetation",
    name: "Zones de végétation (BD TOPO)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Zones de végétation (BD TOPO V3)",
    layerName: "BDTOPO_V3:zone_de_vegetation",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// RISQUES NATURELS (Sprint 4 — Géorisques)
// ═══════════════════════════════════════════════════════════════════════════════

export const RISKS_SOURCES: CatalogItem[] = [
  {
    id: "georisques-ppr",
    name: "Plans de Prévention des Risques (PPR)",
    provider: "Géorisques / BRGM",
    serviceType: "WMS",
    url: "https://mapsref.brgm.fr/wxs/georisques/risques",
    description: "Périmètres PPR naturels et technologiques",
    layerName: "PPR",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "MTE / BRGM Géorisques",
  },
  {
    id: "georisques-argiles",
    name: "Aléa retrait-gonflement argiles",
    provider: "Géorisques / BRGM",
    serviceType: "WMS",
    url: "https://mapsref.brgm.fr/wxs/georisques/risques",
    description: "Zonage aléa argiles (RGA)",
    layerName: "ALEARG",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
  },
  {
    id: "georisques-radon",
    name: "Potentiel radon",
    provider: "Géorisques / BRGM",
    serviceType: "WMS",
    url: "https://mapsref.brgm.fr/wxs/georisques/risques",
    description: "Cartographie potentiel radon des communes",
    layerName: "RADON",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM / IRSN",
  },
  {
    id: "georisques-cavites",
    name: "Cavités souterraines",
    provider: "Géorisques / BRGM",
    serviceType: "WMS",
    url: "https://mapsref.brgm.fr/wxs/georisques/risques",
    description: "Inventaire national des cavités souterraines",
    layerName: "CAVITES",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
  },
  {
    id: "georisques-mvt",
    name: "Mouvements de terrain",
    provider: "Géorisques / BRGM",
    serviceType: "WMS",
    url: "https://mapsref.brgm.fr/wxs/georisques/risques",
    description: "Événements de mouvements de terrain",
    layerName: "MVT",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
  },
  {
    id: "georisques-installations-classees",
    name: "Installations Classées (ICPE)",
    provider: "Géorisques",
    serviceType: "WMS",
    url: "https://mapsref.brgm.fr/wxs/georisques/risques",
    description: "Installations Classées pour la Protection de l'Environnement",
    layerName: "ICPE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "MTE",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// BIODIVERSITÉ & ESPACES PROTÉGÉS (Sprint 4 — INPN / MNHN)
// ═══════════════════════════════════════════════════════════════════════════════

export const BIODIVERSITY_SOURCES: CatalogItem[] = [
  {
    id: "inpn-znieff1",
    name: "ZNIEFF type I",
    provider: "INPN / MNHN",
    serviceType: "WMS",
    url: "https://inpn.mnhn.fr/geoserv/wms",
    description: "Zones Naturelles d'Intérêt Écologique, Faunistique et Floristique type I",
    layerName: "ZNIEFF1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "INPN / MNHN",
  },
  {
    id: "inpn-znieff2",
    name: "ZNIEFF type II",
    provider: "INPN / MNHN",
    serviceType: "WMS",
    url: "https://inpn.mnhn.fr/geoserv/wms",
    description: "ZNIEFF type II (grands ensembles naturels)",
    layerName: "ZNIEFF2",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "INPN / MNHN",
  },
  {
    id: "inpn-natura2000-sic",
    name: "Natura 2000 — SIC/ZSC (Directive Habitats)",
    provider: "INPN / MNHN",
    serviceType: "WMS",
    url: "https://inpn.mnhn.fr/geoserv/wms",
    description: "Sites d'Importance Communautaire Natura 2000",
    layerName: "PROTECTEDSITES.NATURA2000SIC",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "INPN / MNHN",
  },
  {
    id: "inpn-natura2000-zps",
    name: "Natura 2000 — ZPS (Directive Oiseaux)",
    provider: "INPN / MNHN",
    serviceType: "WMS",
    url: "https://inpn.mnhn.fr/geoserv/wms",
    description: "Zones de Protection Spéciale Natura 2000",
    layerName: "PROTECTEDSITES.NATURA2000ZPS",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "INPN / MNHN",
  },
  {
    id: "inpn-parcs-nationaux",
    name: "Parcs Nationaux",
    provider: "INPN / MNHN",
    serviceType: "WMS",
    url: "https://inpn.mnhn.fr/geoserv/wms",
    description: "Parcs nationaux (cœurs et aires d'adhésion)",
    layerName: "PROTECTEDSITES.PN",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "INPN",
  },
  {
    id: "inpn-parcs-regionaux",
    name: "Parcs Naturels Régionaux",
    provider: "INPN / MNHN",
    serviceType: "WMS",
    url: "https://inpn.mnhn.fr/geoserv/wms",
    description: "Parcs Naturels Régionaux (PNR)",
    layerName: "PROTECTEDSITES.PNR",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "INPN",
  },
  {
    id: "inpn-reserves-naturelles",
    name: "Réserves Naturelles Nationales",
    provider: "INPN / MNHN",
    serviceType: "WMS",
    url: "https://inpn.mnhn.fr/geoserv/wms",
    description: "Réserves naturelles nationales",
    layerName: "PROTECTEDSITES.RNN",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "INPN",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// URBANISME RÉGLEMENTAIRE (Sprint 4 — Géoportail de l'Urbanisme)
// ═══════════════════════════════════════════════════════════════════════════════

export const URBAN_PLANNING_SOURCES: CatalogItem[] = [
  {
    id: "gpu-plu-zonage",
    name: "PLU — Zonage",
    provider: "Géoportail Urbanisme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Zonages des Plans Locaux d'Urbanisme",
    layerName: "GPU:zone_urba",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Géoportail de l'Urbanisme",
  },
  {
    id: "gpu-plu-prescription",
    name: "PLU — Prescriptions",
    provider: "Géoportail Urbanisme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Prescriptions urbanistiques (EBC, emplacements réservés...)",
    layerName: "GPU:prescription_surf",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Géoportail de l'Urbanisme",
  },
  {
    id: "gpu-sup",
    name: "Servitudes d'Utilité Publique",
    provider: "Géoportail Urbanisme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Servitudes d'Utilité Publique (SUP)",
    layerName: "GPU:sup_s",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Géoportail de l'Urbanisme",
  },
  {
    id: "fr-cadastre-parcelles",
    name: "Parcelles cadastrales",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Parcelles du cadastre (PCI Express)",
    layerName: "CADASTRALPARCELS.PARCELLAIRE_EXPRESS:parcelle",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "DGFiP / IGN",
    reliable: true,
  },
  {
    id: "fr-cadastre-wmts",
    name: "Parcelles cadastrales (WMTS)",
    provider: "IGN Géoplateforme",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Affichage raster rapide des parcelles cadastrales",
    layerName: "CADASTRALPARCELS.PARCELLAIRE_EXPRESS",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "DGFiP / IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// HYDROGRAPHIE (Sprint 4 — Sandre / SIE)
// ═══════════════════════════════════════════════════════════════════════════════

export const HYDROGRAPHY_SOURCES: CatalogItem[] = [
  {
    id: "ign-hydro-courseau",
    name: "Cours d'eau (BD TOPO)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Tronçons hydrographiques (BD TOPO V3)",
    layerName: "BDTOPO_V3:troncon_hydrographique",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "ign-hydro-surface",
    name: "Surfaces hydrographiques",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Plans d'eau, lacs, étangs (BD TOPO V3)",
    layerName: "BDTOPO_V3:surface_hydrographique",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "sandre-masses-eau-surface",
    name: "Masses d'eau de surface (DCE)",
    provider: "Sandre / OFB",
    serviceType: "WFS",
    url: "https://services.sandre.eaufrance.fr/geo/mdo_FXX",
    description: "Masses d'eau Directive Cadre sur l'Eau",
    layerName: "MasseDEauSurface_FXX",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Sandre / OFB",
  },
  {
    id: "sandre-bassins",
    name: "Bassins hydrographiques",
    provider: "Sandre / OFB",
    serviceType: "WFS",
    url: "https://services.sandre.eaufrance.fr/geo/sbv_FXX",
    description: "Bassins versants topographiques",
    layerName: "BassinVersantTopographique_FXX",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Sandre / OFB",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// OCCUPATION DU SOL (Corine Land Cover)
// ═══════════════════════════════════════════════════════════════════════════════

export const LANDCOVER_SOURCES: CatalogItem[] = [
  {
    id: "clc-2018",
    name: "Corine Land Cover 2018",
    provider: "Copernicus / EEA",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2018_WM/MapServer/WMSServer",
    description: "Occupation du sol européenne 2018 (44 classes)",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "Copernicus Land Monitoring Service / EEA",
    reliable: true,
  },
  {
    id: "clc-2012",
    name: "Corine Land Cover 2012",
    provider: "Copernicus / EEA",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2012_WM/MapServer/WMSServer",
    description: "Occupation du sol européenne 2012",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "Copernicus Land Monitoring Service / EEA",
    reliable: true,
  },
  {
    id: "ocsge-fr",
    name: "OCS GE (Occupation du Sol Grande Échelle)",
    provider: "IGN Géoplateforme",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Occupation du sol française grande échelle",
    layerName: "OCSGE.CONSTRUCTION",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// DÉMOGRAPHIE (démo GeoServer — beta)
// ═══════════════════════════════════════════════════════════════════════════════

export const DEMOGRAPHY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "world-cities-wfs",
    name: "Villes mondiales (Natural Earth)",
    provider: "GeoServer demo",
    serviceType: "WFS",
    url: "https://ahocevar.com/geoserver/wfs",
    description: "Centres de population mondiaux (demo, 10m)",
    layerName: "ne:ne_10m_populated_places",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Natural Earth",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// AGRÉGATION & CATÉGORIES UI
// ═══════════════════════════════════════════════════════════════════════════════

export const ADDITIONAL_DATA_SOURCES: CatalogItem[] = [
  ...BASEMAP_SOURCES,
  ...TOPOGRAPHIC_RASTER_SOURCES,
  ...SATELLITE_RASTER_SOURCES,
  ...LIDAR_SOURCES,
  ...ADMINISTRATIVE_VECTOR_SOURCES,
  ...INFRASTRUCTURE_VECTOR_SOURCES,
  ...FORESTRY_VECTOR_SOURCES,
  ...RISKS_SOURCES,
  ...BIODIVERSITY_SOURCES,
  ...URBAN_PLANNING_SOURCES,
  ...HYDROGRAPHY_SOURCES,
  ...LANDCOVER_SOURCES,
  ...DEMOGRAPHY_VECTOR_SOURCES,
];

export function getAllDataSources(): CatalogItem[] {
  return ADDITIONAL_DATA_SOURCES;
}

export const DATA_SOURCE_CATEGORIES = {
  base: {
    name: "Fonds de carte",
    description: "Cartes de base (OSM, Esri, Carto)",
    sources: BASEMAP_SOURCES,
  },
  topographic: {
    name: "Topographie IGN",
    description: "Cartes topographiques IGN (SCAN 25, Plan IGN, cartes historiques)",
    sources: TOPOGRAPHIC_RASTER_SOURCES,
  },
  satellite: {
    name: "Imagerie aérienne",
    description: "Orthophotos IGN récentes, historiques et infrarouge",
    sources: SATELLITE_RASTER_SOURCES,
  },
  lidar: {
    name: "LiDAR & Altimétrie",
    description: "LiDAR HD et RGE ALTI — MNT, MNS, ombrage",
    sources: LIDAR_SOURCES,
  },
  administrative: {
    name: "Administratif",
    description: "Communes, départements, régions, EPCI",
    sources: ADMINISTRATIVE_VECTOR_SOURCES,
  },
  infrastructure: {
    name: "Bâti & Réseaux",
    description: "Bâtiments, routes, voies ferrées, adresses (BD TOPO)",
    sources: INFRASTRUCTURE_VECTOR_SOURCES,
  },
  forestry: {
    name: "Forêts",
    description: "BD Forêt V2 (formations, essences) et végétation",
    sources: FORESTRY_VECTOR_SOURCES,
  },
  risks: {
    name: "Risques naturels",
    description: "PPR, argiles, radon, cavités, mouvements de terrain, ICPE (Géorisques)",
    sources: RISKS_SOURCES,
  },
  biodiversity: {
    name: "Biodiversité",
    description: "ZNIEFF, Natura 2000, Parcs Nationaux/Régionaux, Réserves (INPN)",
    sources: BIODIVERSITY_SOURCES,
  },
  urbanPlanning: {
    name: "Urbanisme & Cadastre",
    description: "PLU, SUP, parcelles cadastrales (Géoportail de l'Urbanisme)",
    sources: URBAN_PLANNING_SOURCES,
  },
  hydrography: {
    name: "Hydrographie",
    description: "Cours d'eau, masses d'eau, bassins versants (IGN + Sandre)",
    sources: HYDROGRAPHY_SOURCES,
  },
  landcover: {
    name: "Occupation du sol",
    description: "Corine Land Cover et OCS GE (IGN)",
    sources: LANDCOVER_SOURCES,
  },
  demography: {
    name: "Démographie",
    description: "Données démographiques mondiales (beta)",
    sources: DEMOGRAPHY_VECTOR_SOURCES,
  },
};
