// Sources de données supplémentaires pour GeoSylva AI QGIS
// Organisées par catégories pour une navigation facile
// WMS, WMTS, WFS, WCS, XYZ, ArcGIS, etc.

import { CatalogItem } from "./catalog";

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIES : FONDS DE CARTE (RASTER)
// ═══════════════════════════════════════════════════════════════════════════════

export const BASEMAP_SOURCES: CatalogItem[] = [
  // === OpenStreetMap ===
  {
    id: "osm-standard",
    name: "OpenStreetMap Standard",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    description: "Fond OSM standard",
    zMin: 0,
    zMax: 19,
    attribution: "OpenStreetMap contributors",
  },
  {
    id: "osm-hot",
    name: "OSM HOT",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
    description: "OSM Humanitarian",
    zMin: 0,
    zMax: 19,
    attribution: "OpenStreetMap contributors",
  },
  {
    id: "osm-cycle",
    name: "OSM Cycle Map",
    provider: "Thunderforest",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=YOUR_KEY",
    description: "Carte cyclable (clé API requise)",
    zMin: 0,
    zMax: 18,
    requiresKey: true,
    attribution: "OpenStreetMap, Thunderforest",
  },
  {
    id: "osm-transport",
    name: "OSM Transport",
    provider: "Thunderforest",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/transport/{z}/{x}/{y}.png?apikey=YOUR_KEY",
    description: "Transports publics (clé API requise)",
    zMin: 0,
    zMax: 18,
    requiresKey: true,
    attribution: "OpenStreetMap, Thunderforest",
  },
  {
    id: "osm-outdoors",
    name: "OSM Outdoors",
    provider: "Thunderforest",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey=YOUR_KEY",
    description: "Randonnée nature (clé API requise)",
    zMin: 0,
    zMax: 18,
    requiresKey: true,
    attribution: "OpenStreetMap, Thunderforest",
  },
  {
    id: "osm-landscape",
    name: "OSM Landscape",
    provider: "Thunderforest",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/landscape/{z}/{x}/{y}.png?apikey=YOUR_KEY",
    description: "Paysage (clé API requise)",
    zMin: 0,
    zMax: 18,
    requiresKey: true,
    attribution: "OpenStreetMap, Thunderforest",
  },

  // === CartoDB ===
  {
    id: "carto-dark",
    name: "Carto Dark Matter",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png",
    description: "Fond sombre pour visualisation analytique",
    zMin: 0,
    zMax: 20,
    reliable: true,
    attribution: "OpenStreetMap, CARTO",
  },
  {
    id: "carto-positron",
    name: "Carto Positron",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
    description: "Fond clair minimaliste",
    zMin: 0,
    zMax: 20,
    reliable: true,
    attribution: "OpenStreetMap, CARTO",
  },
  {
    id: "carto-voyager",
    name: "Carto Voyager",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png",
    description: "Style voyage",
    zMin: 0,
    zMax: 20,
    reliable: true,
    attribution: "OpenStreetMap, CARTO",
  },

  // === Esri ===
  {
    id: "esri-world-imagery",
    name: "Esri World Imagery",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",
    description: "Imagerie mondiale ArcGIS REST",
    attribution: "Esri, Maxar, Earthstar Geographics",
  },
  {
    id: "esri-street",
    name: "Esri World Street",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",
    description: "Rues du monde",
    attribution: "Esri",
  },
  {
    id: "esri-topo",
    name: "Esri World Topo",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer",
    description: "Topographie mondiale",
    attribution: "Esri",
  },
  {
    id: "esri-physical",
    name: "Esri World Physical",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer",
    description: "Physique du monde",
    attribution: "Esri",
  },
  {
    id: "esri-shaded",
    name: "Esri World Shaded Relief",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer",
    description: "Relief ombré",
    attribution: "Esri",
  },
  {
    id: "esri-terrain",
    name: "Esri World Terrain",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer",
    description: "Terrain de base",
    attribution: "Esri",
  },
  {
    id: "esri-natgeo",
    name: "Esri National Geographic",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer",
    description: "Carte National Geographic",
    attribution: "Esri, National Geographic",
  },
];

export const FORESTRY_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "ign-forets",
    name: "Forêts IGN (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Massifs forestiers IGN",
    layerName: "FORETS:MASSIF_FORESTIER",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-forets-publiques",
    name: "Forêts publiques (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Massifs forestiers et peuplements (IGN)",
    layerName: "FORETS.PUBLIQUES:formation_vegetale",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "ign-peuplements",
    name: "Peuplements forestiers (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Peuplements forestiers",
    layerName: "FORETS:PEUPLEMENTS",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-vegetation",
    name: "Végétation (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Zones végétalisées",
    layerName: "BDTOPO_BDD_WLD_WGS84G:ZONE_VEGETATION",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "copernicus-forest-cover",
    name: "Couverture forestière (WMS)",
    provider: "Copernicus Land",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2018_WM/MapServer/WMSServer",
    description: "Couverture forestière Corine Land Cover 2018 (forestière = classe 311-313)",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "EEA / Copernicus Land Monitoring Service",
    reliable: true,
  },
  {
    id: "copernicus-ndvi",
    name: "NDVI MODIS (WMS)",
    provider: "NASA GIBS",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Indice de végétation NDVI MODIS (NASA, gratuit, pas de clé requise)",
    layerName: "MODIS_Terra_NDVI_8Day",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA GIBS",
    reliable: true,
  },
  {
    id: "nasa-ndvi",
    name: "MODIS NDVI (WMS)",
    provider: "NASA",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Indice de végétation MODIS",
    layerName: "MODIS_Terra_NDVI",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA",
  },
  {
    id: "nasa-fire",
    name: "MODIS Fire (WMS)",
    provider: "NASA",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Détecteur de feux forestiers",
    layerName: "MODIS_Terra_Fire_Thermal_Anomalies",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA",
  },
];

export const TOPOGRAPHIC_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "ign-scan25",
    name: "SCAN25 (IGN)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Carte topographique au 1:25000",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-scan50",
    name: "SCAN50 (IGN)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Carte topographique au 1:50000",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN50",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-scan100",
    name: "SCAN100 (IGN)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Carte topographique au 1:100000",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN100",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-planign",
    name: "Plan IGN V2 (WMTS)",
    provider: "IGN",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Fond plan IGN V2 via WMTS",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-alti",
    name: "ALTI (MNT) (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Modèle numérique de terrain",
    layerName: "ELEVATION.ELEVATIONGRIDCOVERAGE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
];

export const SATELLITE_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "geopf-wms-raster",
    name: "Géoplateforme Ortho",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Orthophotos nationales IGN via WMS",
    layerName: "ORTHOIMAGERY.ORTHOPHOTOS",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "nasa-gibs-wms",
    name: "NASA GIBS TrueColor",
    provider: "NASA",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Imagerie mondiale quasi temps réel",
    layerName: "MODIS_Terra_CorrectedReflectance_TrueColor",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA",
  },
  {
    id: "copernicus-sentinel2",
    name: "Sentinel-2 TrueColor (WMS)",
    provider: "NASA GIBS",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Imagerie Sentinel-2 couleurs naturelles via NASA GIBS (gratuit)",
    layerName: "Sentinel_2_L2A_TrueColor",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA GIBS / Copernicus Sentinel",
    reliable: true,
  },
];

export const ENVIRONMENTAL_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "corine",
    name: "Corine Land Cover",
    provider: "EEA",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2018/MapServer/WMSServer",
    description: "Occupation du sol Corine",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "EEA",
  },
];

export const CLIMATE_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "noaa-radar",
    name: "NOAA Radar météo (WMS)",
    provider: "NOAA",
    serviceType: "WMS",
    url: "https://opengeo.ncep.noaa.gov/geoserver/conus/conus_bref_qc/ows",
    description: "Radar météo NEXRAD temps réel (NOAA)",
    layerName: "conus_bref_qc",
    format: "image/png",
    crs: "EPSG:4326",
    attribution: "NOAA",
    reliable: true,
  },
  {
    id: "noaa-precipitation",
    name: "NOAA Précipitations (WMS)",
    provider: "NOAA",
    serviceType: "WMS",
    url: "https://opengeo.ncep.noaa.gov/geoserver/conus/conus_precip_24h/ows",
    description: "Cumul de précipitations 24h NOAA",
    layerName: "conus_precip_24h",
    format: "image/png",
    crs: "EPSG:4326",
    attribution: "NOAA",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIES : DONNÉES VECTEURS (WFS)
// ═══════════════════════════════════════════════════════════════════════════════

export const ADMINISTRATIVE_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-communes-wfs",
    name: "Communes France (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Contours des communes françaises",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:commune",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-departements-wfs",
    name: "Départements France (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Contours des départements français",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:departement",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-regions-wfs",
    name: "Régions France (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Contours des régions françaises",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:region",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-epci-wfs",
    name: "EPCI France (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Intercommunalités françaises",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:epci",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
];

export const FORESTRY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-forets-publiques",
    name: "Forêts publiques France (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Zones de végétation / forêts (BD TOPO V3)",
    layerName: "BDTOPO_V3:zone_de_vegetation",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-peuplements-forestiers",
    name: "Peuplements forestiers (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Peuplements forestiers (BD Forêts)",
    layerName: "BDFORET_V2:formation_vegetale",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-essences-forestieres",
    name: "Essences forestières (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Types d'essences forestières (BD Forêts)",
    layerName: "BDFORET_V2:essences",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-zones-agricoles",
    name: "Zones agricoles (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Zones agricoles (BD TOPO V3)",
    layerName: "BDTOPO_V3:zone_d_activite_ou_d_interet",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-vignes",
    name: "Vignes France (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Vignes et vignobles",
    layerName: "BDTOPO_V3:zone_de_vegetation",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
];

export const GEOLOGY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-geologie-brgm",
    name: "Carte géologique France (WMS)",
    provider: "BRGM",
    serviceType: "WMS",
    url: "https://geoservices.brgm.fr/geologie",
    description: "Carte géologique de la France 1/1M (BRGM)",
    layerName: "GEOLOGIE:COUCHE_GEOLOGIQUE_1M",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
    reliable: true,
  },
  {
    id: "fr-mines-brgm",
    name: "Mines et carrières (WMS)",
    provider: "BRGM",
    serviceType: "WMS",
    url: "https://geoservices.brgm.fr/mines",
    description: "Sites miniers et carrières France",
    layerName: "MINES:SITE_MINIER",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
  },
  {
    id: "fr-sismic-brgm",
    name: "Zones sismiques (WMS)",
    provider: "BRGM",
    serviceType: "WMS",
    url: "https://geoservices.brgm.fr/risques",
    description: "Zonage sismique France",
    layerName: "ALEA_SISMIQUE:ZONE_SISMIQUE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
  },
];

export const INFRASTRUCTURE_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-reseau-routier",
    name: "Réseau routier (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Routes (BD TOPO V3)",
    layerName: "BDTOPO_V3:route",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-autoroutes",
    name: "Autoroutes (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Autoroutes (BD TOPO V3)",
    layerName: "BDTOPO_V3:route",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-voies-ferrees",
    name: "Voies ferrées (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Voies ferrées (BD TOPO V3)",
    layerName: "BDTOPO_V3:troncon_de_voie_ferree",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
];

export const URBAN_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-bati-3d",
    name: "Bâtiments France (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Bâtiments (BD TOPO V3)",
    layerName: "BDTOPO_V3:batiment",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-zones-urbanisees",
    name: "Zones urbanisées (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Zones d'activité (BD TOPO V3)",
    layerName: "BDTOPO_V3:zone_d_activite_ou_d_interet",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-adresse",
    name: "Adresses (WFS)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Adresses postales (BD TOPO V3)",
    layerName: "BDTOPO_V3:adresse",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
];

export const SOIL_WATER_CAPACITY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-rum-sols",
    name: "Réserve Utile Maximale des sols (WMS)",
    provider: "BRGM",
    serviceType: "WMS",
    url: "https://geoservices.brgm.fr/risques",
    description: "Sols et aléas géologiques via BRGM (approximation RUM)",
    layerName: "ALEA_SISMIQUE:ZONE_SISMIQUE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
  },
  {
    id: "fr-capacite-retention",
    name: "Corine Land Cover - Occupation des sols (WMS)",
    provider: "EEA",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2018/MapServer/WMSServer",
    description: "Occupation des sols Corine Land Cover 2018 (EEA)",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "EEA",
    reliable: true,
  },
  {
    id: "fr-texture-sols",
    name: "BD TOPO Sol (WFS IGN)",
    provider: "IGN Géoplateforme",
    serviceType: "WFS",
    url: "https://data.geopf.fr/wfs/ows",
    description: "Zone de végétation (proxy sol/végétation BD TOPO V3)",
    layerName: "BDTOPO_V3:zone_de_vegetation",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
    reliable: true,
  },
  {
    id: "fr-profondeur-sol",
    name: "Formations superficielles (WMS BRGM)",
    provider: "BRGM",
    serviceType: "WMS",
    url: "https://geoservices.brgm.fr/geologie",
    description: "Géologie de surface et formations superficielles (BRGM)",
    layerName: "GEOLOGIE:COUCHE_GEOLOGIQUE_1M",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "BRGM",
    reliable: true,
  },
  {
    id: "eu-soil-water-capacity",
    name: "European Soil (WMS EEA)",
    provider: "EEA",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2018/MapServer/WMSServer",
    description: "Données sols Europe via EEA Corine Land Cover",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "European Commission / EEA",
    reliable: true,
  },
  {
    id: "eu-soil-moisture",
    name: "Hydrologie européenne (WMS EEA)",
    provider: "EEA",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Water/WFD_SurfaceWater_Bodies/MapServer/WMSServer",
    description: "Masses d'eau et hydrologie européenne (Directive Cadre sur l'Eau)",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "European Commission / EEA",
  },
];

export const DEMOGRAPHY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "world-cities-wfs",
    name: "World Cities (WFS)",
    provider: "Natural Earth / GeoServer",
    serviceType: "WFS",
    url: "https://ahocevar.com/geoserver/wfs",
    description: "Villes du monde (Natural Earth)",
    layerName: "ne:ne_10m_populated_places",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Natural Earth",
    reliable: true,
  },
  {
    id: "population-centers-wfs",
    name: "Population Centers (WFS)",
    provider: "Natural Earth",
    serviceType: "WFS",
    url: "https://ahocevar.com/geoserver/wfs",
    description: "Centres de population",
    layerName: "ne:ne_10m_populated_places",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Natural Earth",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// EXPORTATION POUR COMPATIBILITÉ
// ═══════════════════════════════════════════════════════════════════════════════

export const ADDITIONAL_DATA_SOURCES: CatalogItem[] = [
  ...BASEMAP_SOURCES,
  ...FORESTRY_RASTER_SOURCES,
  ...TOPOGRAPHIC_RASTER_SOURCES,
  ...SATELLITE_RASTER_SOURCES,
  ...ENVIRONMENTAL_RASTER_SOURCES,
  ...CLIMATE_RASTER_SOURCES,
  ...ADMINISTRATIVE_VECTOR_SOURCES,
  ...FORESTRY_VECTOR_SOURCES,
  ...GEOLOGY_VECTOR_SOURCES,
  ...INFRASTRUCTURE_VECTOR_SOURCES,
  ...URBAN_VECTOR_SOURCES,
  ...SOIL_WATER_CAPACITY_VECTOR_SOURCES,
  ...DEMOGRAPHY_VECTOR_SOURCES,
];

export function getAllDataSources(): CatalogItem[] {
  // Import dynamique évité — utiliser ALL_DATA_SOURCES de catalog.ts à la place
  return ADDITIONAL_DATA_SOURCES;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIES ORGANISÉES POUR L'INTERFACE
// ═══════════════════════════════════════════════════════════════════════════════

export const DATA_SOURCE_CATEGORIES = {
  base: {
    name: "Fonds de carte",
    description: "Cartes de base pour navigation",
    sources: BASEMAP_SOURCES,
  },
  forestry: {
    name: "Forêts",
    description: "Données forestières (raster et vecteur)",
    sources: [...FORESTRY_RASTER_SOURCES, ...FORESTRY_VECTOR_SOURCES],
  },
  topographic: {
    name: "Topographie",
    description: "Cartes topographiques et MNT",
    sources: TOPOGRAPHIC_RASTER_SOURCES,
  },
  satellite: {
    name: "Satellite",
    description: "Imagerie satellite et aérienne",
    sources: SATELLITE_RASTER_SOURCES,
  },
  environmental: {
    name: "Environnement",
    description: "Données environnementales et climatiques",
    sources: [...ENVIRONMENTAL_RASTER_SOURCES, ...CLIMATE_RASTER_SOURCES],
  },
  administrative: {
    name: "Administratif",
    description: "Limites administratives",
    sources: ADMINISTRATIVE_VECTOR_SOURCES,
  },
  geology: {
    name: "Géologie",
    description: "Données géologiques et naturelles",
    sources: GEOLOGY_VECTOR_SOURCES,
  },
  infrastructure: {
    name: "Infrastructure",
    description: "Réseaux de transport",
    sources: INFRASTRUCTURE_VECTOR_SOURCES,
  },
  urban: {
    name: "Urbanisme",
    description: "Bâti et zones urbanisées",
    sources: URBAN_VECTOR_SOURCES,
  },
  soil: {
    name: "Sols et RUM",
    description: "Réserve utile maximale des sols et pédologie",
    sources: SOIL_WATER_CAPACITY_VECTOR_SOURCES,
  },
  demography: {
    name: "Démographie",
    description: "Population et villes",
    sources: DEMOGRAPHY_VECTOR_SOURCES,
  },
};
