// Sources de données supplémentaires pour GeoSylva AI QGIS
// Organisées par catégories pour une navigation facile
// WMS, WMTS, WFS, WCS, XYZ, ArcGIS, etc.

import { CatalogItem } from "./catalog";

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIES : FONDS DE CARTE (RASTER)
// ═══════════════════════════════════════════════════════════════════════════════

export const BASEMAP_SOURCES: CatalogItem[] = [
  // === OpenStreetMap ===
  {
    id: "osm-standard",
    name: "OpenStreetMap Standard",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
    description: "Fond OSM standard",
    zMin: 0,
    zMax: 19,
    attribution: "OpenStreetMap contributors",
  },
  {
    id: "osm-hot",
    name: "OSM HOT",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
    description: "OSM Humanitarian",
    zMin: 0,
    zMax: 19,
    attribution: "OpenStreetMap contributors",
  },
  {
    id: "osm-cycle",
    name: "OSM Cycle Map",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/cycle/{z}/{x}/{y}.png",
    description: "Carte cyclable",
    zMin: 0,
    zMax: 18,
    attribution: "OpenStreetMap, Thunderforest",
  },
  {
    id: "osm-transport",
    name: "OSM Transport",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/transport/{z}/{x}/{y}.png",
    description: "Transports publics",
    zMin: 0,
    zMax: 18,
    attribution: "OpenStreetMap, Thunderforest",
  },
  {
    id: "osm-outdoors",
    name: "OSM Outdoors",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/outdoors/{z}/{x}/{y}.png",
    description: "Randonnée nature",
    zMin: 0,
    zMax: 18,
    attribution: "OpenStreetMap, Thunderforest",
  },
  {
    id: "osm-landscape",
    name: "OSM Landscape",
    provider: "OSM",
    serviceType: "XYZ",
    url: "https://a.tile.thunderforest.com/landscape/{z}/{x}/{y}.png",
    description: "Paysage",
    zMin: 0,
    zMax: 18,
    attribution: "OpenStreetMap, Thunderforest",
  },

  // === CartoDB ===
  {
    id: "carto-dark",
    name: "Carto Dark Matter",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
    description: "Fond sombre pour visualisation analytique",
    zMin: 0,
    zMax: 20,
    attribution: "OpenStreetMap, CARTO",
  },
  {
    id: "carto-positron",
    name: "Carto Positron",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
    description: "Fond clair minimaliste",
    zMin: 0,
    zMax: 20,
    attribution: "OpenStreetMap, CARTO",
  },
  {
    id: "carto-voyager",
    name: "Carto Voyager",
    provider: "Carto",
    serviceType: "XYZ",
    url: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png",
    description: "Style voyage",
    zMin: 0,
    zMax: 20,
    attribution: "OpenStreetMap, CARTO",
  },

  // === Esri ===
  {
    id: "esri-world-imagery",
    name: "Esri World Imagery",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",
    description: "Imagerie mondiale ArcGIS REST",
    attribution: "Esri, Maxar, Earthstar Geographics",
  },
  {
    id: "esri-street",
    name: "Esri World Street",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",
    description: "Rues du monde",
    attribution: "Esri",
  },
  {
    id: "esri-topo",
    name: "Esri World Topo",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer",
    description: "Topographie mondiale",
    attribution: "Esri",
  },
  {
    id: "esri-physical",
    name: "Esri World Physical",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Physical_Map/MapServer",
    description: "Physique du monde",
    attribution: "Esri",
  },
  {
    id: "esri-shaded",
    name: "Esri World Shaded Relief",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer",
    description: "Relief ombré",
    attribution: "Esri",
  },
  {
    id: "esri-terrain",
    name: "Esri World Terrain",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer",
    description: "Terrain de base",
    attribution: "Esri",
  },
  {
    id: "esri-natgeo",
    name: "Esri National Geographic",
    provider: "Esri",
    serviceType: "ArcGISMapServer",
    url: "https://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer",
    description: "Carte National Geographic",
    attribution: "Esri, National Geographic",
  },
];

export const FORESTRY_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "ign-forets",
    name: "Forêts IGN (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Massifs forestiers IGN",
    layerName: "FORETS:MASSIF_FORESTIER",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-forets-publiques",
    name: "Forêts publiques (WMS)",
    provider: "ONF",
    serviceType: "WMS",
    url: "https://geoservices.onf.fr/forets/wms",
    description: "Domaine forestier public ONF",
    layerName: "FORETS_PUBLIQUES:DOMAINE_FORESTIER",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "Office National des Forêts",
  },
  {
    id: "ign-peuplements",
    name: "Peuplements forestiers (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Peuplements forestiers",
    layerName: "FORETS:PEUPLEMENTS",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-vegetation",
    name: "Végétation (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Zones végétalisées",
    layerName: "BDTOPO_BDD_WLD_WGS84G:ZONE_VEGETATION",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "copernicus-forest-cover",
    name: "Couverture forestière (WMS)",
    provider: "Copernicus",
    serviceType: "WMS",
    url: "https://land.copernicus.vgt.vito.be/ogc/wms",
    description: "Couverture forestière mondiale",
    layerName: "FOREST_COVER",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "Copernicus",
  },
  {
    id: "copernicus-ndvi",
    name: "NDVI Sentinel-2 (WMS)",
    provider: "Copernicus",
    serviceType: "WMS",
    url: "https://services.sentinel-hub.com/ogc/wms/",
    description: "Indice de végétation NDVI",
    layerName: "NDVI",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "Copernicus Sentinel data",
  },
  {
    id: "nasa-ndvi",
    name: "MODIS NDVI (WMS)",
    provider: "NASA",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Indice de végétation MODIS",
    layerName: "MODIS_Terra_NDVI",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA",
  },
  {
    id: "nasa-fire",
    name: "MODIS Fire (WMS)",
    provider: "NASA",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Détecteur de feux forestiers",
    layerName: "MODIS_Terra_Fire_Thermal_Anomalies",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA",
  },
];

export const TOPOGRAPHIC_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "ign-scan25",
    name: "SCAN25 (IGN)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Carte topographique au 1:25000",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-scan50",
    name: "SCAN50 (IGN)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Carte topographique au 1:50000",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN50",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-scan100",
    name: "SCAN100 (IGN)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Carte topographique au 1:100000",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN100",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-planign",
    name: "Plan IGN V2 (WMTS)",
    provider: "IGN",
    serviceType: "WMTS",
    url: "https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetCapabilities",
    description: "Fond plan IGN V2 via WMTS",
    layerName: "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
    tileMatrixSet: "PM",
    style: "normal",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "ign-alti",
    name: "ALTI (MNT) (WMS)",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Modèle numérique de terrain",
    layerName: "ELEVATION.ELEVATIONGRIDCOVERAGE",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
];

export const SATELLITE_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "geopf-wms-raster",
    name: "Géoplateforme Ortho",
    provider: "IGN",
    serviceType: "WMS",
    url: "https://data.geopf.fr/wms-r",
    description: "Orthophotos nationales IGN via WMS",
    layerName: "ORTHOIMAGERY.ORTHOPHOTOS",
    format: "image/jpeg",
    crs: "EPSG:3857",
    attribution: "IGN",
  },
  {
    id: "nasa-gibs-wms",
    name: "NASA GIBS TrueColor",
    provider: "NASA",
    serviceType: "WMS",
    url: "https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi",
    description: "Imagerie mondiale quasi temps réel",
    layerName: "MODIS_Terra_CorrectedReflectance_TrueColor",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NASA",
  },
  {
    id: "copernicus-sentinel2",
    name: "Sentinel-2",
    provider: "Copernicus",
    serviceType: "WMS",
    url: "https://services.sentinel-hub.com/ogc/wms/",
    description: "Imagerie Sentinel-2",
    layerName: "S2",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "Copernicus Sentinel data",
  },
];

export const ENVIRONMENTAL_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "corine",
    name: "Corine Land Cover",
    provider: "EEA",
    serviceType: "WMS",
    url: "https://image.discomap.eea.europa.eu/arcgis/services/Corine/CLC2018/MapServer/WMSServer",
    description: "Occupation du sol Corine",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "EEA",
  },
];

export const CLIMATE_RASTER_SOURCES: CatalogItem[] = [
  {
    id: "noaa-radar",
    name: "NOAA Radar",
    provider: "NOAA",
    serviceType: "WMS",
    url: "https://nowcoast.noaa.gov/arcgis/services/nowcoast/radar_meteo_imagery_nexrad/MapServer/WMServer",
    description: "Radar météo",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NOAA",
  },
  {
    id: "noaa-precipitation",
    name: "NOAA Precipitation",
    provider: "NOAA",
    serviceType: "WMS",
    url: "https://nowcoast.noaa.gov/arcgis/services/nowcoast/analysis_meteocean_surface_sfc_precipitation/MapServer/WMServer",
    description: "Précipitations",
    layerName: "1",
    format: "image/png",
    crs: "EPSG:3857",
    attribution: "NOAA",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIES : DONNÉES VECTEURS (WFS)
// ═══════════════════════════════════════════════════════════════════════════════

export const ADMINISTRATIVE_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-communes-wfs",
    name: "Communes France (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Contours des communes françaises",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:COMMUNE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-departements-wfs",
    name: "Départements France (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Contours des départements français",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:DEPARTEMENT",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-regions-wfs",
    name: "Régions France (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Contours des régions françaises",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:REGION",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-epci-wfs",
    name: "EPCI France (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Intercommunalités françaises",
    layerName: "LIMITES_ADMINISTRATIVES_EXPRESS:EPCI",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
];

export const FORESTRY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-forets-publiques",
    name: "Forêts publiques France (WFS)",
    provider: "ONF",
    serviceType: "WFS",
    url: "https://geoservices.onf.fr/forets/wfs",
    description: "Domaine forestier public",
    layerName: "FORETS_PUBLIQUES:DOMAINE_FORESTIER",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Office National des Forêts",
  },
  {
    id: "fr-peuplements-forestiers",
    name: "Peuplements forestiers (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Peuplements forestiers",
    layerName: "FORETS:PEUPLEMENTS_FORESTIERS",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-essences-forestieres",
    name: "Essences forestières (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Types d'essences forestières",
    layerName: "FORETS:ESSENCES",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-zones-agricoles",
    name: "Zones agricoles (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Zones agricoles",
    layerName: "LANDCOVER:ZONE_AGRICOLE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-vignes",
    name: "Vignes France (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Vignes et vignobles",
    layerName: "LANDCOVER:VIGNE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
];

export const GEOLOGY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-geologie-brgm",
    name: "Carte géologique France (WFS)",
    provider: "BRGM",
    serviceType: "WFS",
    url: "https://geoservices.brgm.fr/geologie/wfs",
    description: "Carte géologique de la France",
    layerName: "GEOLOGIE:CARTE_GEOLOGIQUE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "BRGM",
  },
  {
    id: "fr-mines-brgm",
    name: "Mines et carrières (WFS)",
    provider: "BRGM",
    serviceType: "WFS",
    url: "https://geoservices.brgm.fr/mines/wfs",
    description: "Mines et carrières de France",
    layerName: "MINES:MINES",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "BRGM",
  },
  {
    id: "fr-sismic-brgm",
    name: "Zones sismiques (WFS)",
    provider: "BRGM",
    serviceType: "WFS",
    url: "https://geoservices.brgm.fr/sismicite/wfs",
    description: "Zones sismiques de France",
    layerName: "SISMICITE:ZONES_SISMIQUES",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "BRGM",
  },
];

export const INFRASTRUCTURE_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-reseau-routier",
    name: "Réseau routier (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Routes principales",
    layerName: "BDTOPO_BDD_WLD_WGS84G:ROUTE_PRINCIPALE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-autoroutes",
    name: "Autoroutes (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Autoroutes",
    layerName: "BDTOPO_BDD_WLD_WGS84G:AUTOROUTE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-voies-ferrées",
    name: "Voies ferrées (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Voies ferrées",
    layerName: "BDTOPO_BDD_WLD_WGS84G:VOIE_FERREE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
];

export const URBAN_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-bati-3d",
    name: "Bâti 3D France (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Bâtiments en 3D",
    layerName: "BDTOPO_BDD_WLD_WGS84G:BATIMENT",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-zones-urbanisées",
    name: "Zones urbanisées (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Zones urbanisées",
    layerName: "BDTOPO_BDD_WLD_WGS84G:ZONE_URBAINE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-adresse",
    name: "Adresses (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Adresses postales",
    layerName: "ADRESSE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
];

export const SOIL_WATER_CAPACITY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "fr-rum-sols",
    name: "Réserve Utile Maximale des sols (WFS)",
    provider: "INRAE",
    serviceType: "WFS",
    url: "https://data.inrae.fr/geoserver/sols/wfs",
    description: "Réserve utile maximale des sols France",
    layerName: "SOLS:RUM",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "INRAE",
  },
  {
    id: "fr-capacite-retention",
    name: "Capacité de rétention eau sols (WFS)",
    provider: "INRAE",
    serviceType: "WFS",
    url: "https://data.inrae.fr/geoserver/sols/wfs",
    description: "Capacité de rétention en eau des sols",
    layerName: "SOLS:CAPACITE_RETENTION",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "INRAE",
  },
  {
    id: "fr-texture-sols",
    name: "Texture des sols (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Texture et composition des sols",
    layerName: "SOLS:TEXTURE",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "fr-profondeur-sol",
    name: "Profondeur du sol (WFS)",
    provider: "IGN",
    serviceType: "WFS",
    url: "https://wxs.ign.fr/choisirgeoportail/geoportail/wfs",
    description: "Profondeur des horizons de sol",
    layerName: "SOLS:PROFONDEUR",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "IGN",
  },
  {
    id: "eu-soil-water-capacity",
    name: "European Soil Water Capacity (WFS)",
    provider: "EUSOIL",
    serviceType: "WFS",
    url: "https://esdac.jrc.ec.europa.eu/arcgis/services/Soil/Soil_Water_Capacity/MapServer/WFSServer",
    description: "Capacité de rétention en eau des sols européens",
    layerName: "0",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "European Commission",
  },
  {
    id: "eu-soil-moisture",
    name: "European Soil Moisture (WFS)",
    provider: "EUSOIL",
    serviceType: "WFS",
    url: "https://esdac.jrc.ec.europa.eu/arcgis/services/Soil/Soil_Moisture/MapServer/WFSServer",
    description: "Teneur en eau des sols européens",
    layerName: "0",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "European Commission",
  },
];

export const DEMOGRAPHY_VECTOR_SOURCES: CatalogItem[] = [
  {
    id: "world-cities-wfs",
    name: "World Cities (WFS)",
    provider: "GeoNames",
    serviceType: "WFS",
    url: "https://www.geonames.org/wfs",
    description: "Villes du monde",
    layerName: "cities",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "GeoNames",
  },
  {
    id: "population-centers-wfs",
    name: "Population Centers (WFS)",
    provider: "Natural Earth",
    serviceType: "WFS",
    url: "https://ahocevar.com/geoserver/wfs",
    description: "Centres de population",
    layerName: "ne:ne_10m_populated_places",
    version: "2.0.0",
    crs: "EPSG:4326",
    attribution: "Natural Earth",
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// EXPORTATION POUR COMPATIBILITÉ
// ═══════════════════════════════════════════════════════════════════════════════

export const ADDITIONAL_DATA_SOURCES: CatalogItem[] = [
  ...BASEMAP_SOURCES,
  ...FORESTRY_RASTER_SOURCES,
  ...TOPOGRAPHIC_RASTER_SOURCES,
  ...SATELLITE_RASTER_SOURCES,
  ...ENVIRONMENTAL_RASTER_SOURCES,
  ...CLIMATE_RASTER_SOURCES,
  ...ADMINISTRATIVE_VECTOR_SOURCES,
  ...FORESTRY_VECTOR_SOURCES,
  ...GEOLOGY_VECTOR_SOURCES,
  ...INFRASTRUCTURE_VECTOR_SOURCES,
  ...URBAN_VECTOR_SOURCES,
  ...SOIL_WATER_CAPACITY_VECTOR_SOURCES,
  ...DEMOGRAPHY_VECTOR_SOURCES,
];

export function getAllDataSources(): CatalogItem[] {
  // Combine avec CARTOGRAPHIC_CATALOG du fichier catalog.ts
  const { CARTOGRAPHIC_CATALOG } = require("./catalog");
  return [...CARTOGRAPHIC_CATALOG, ...ADDITIONAL_DATA_SOURCES];
}

// ═══════════════════════════════════════════════════════════════════════════════
// CATÉGORIES ORGANISÉES POUR L'INTERFACE
// ═══════════════════════════════════════════════════════════════════════════════

export const DATA_SOURCE_CATEGORIES = {
  base: {
    name: "Fonds de carte",
    description: "Cartes de base pour navigation",
    sources: BASEMAP_SOURCES,
  },
  forestry: {
    name: "Forêts",
    description: "Données forestières (raster et vecteur)",
    sources: [...FORESTRY_RASTER_SOURCES, ...FORESTRY_VECTOR_SOURCES],
  },
  topographic: {
    name: "Topographie",
    description: "Cartes topographiques et MNT",
    sources: TOPOGRAPHIC_RASTER_SOURCES,
  },
  satellite: {
    name: "Satellite",
    description: "Imagerie satellite et aérienne",
    sources: SATELLITE_RASTER_SOURCES,
  },
  environmental: {
    name: "Environnement",
    description: "Données environnementales et climatiques",
    sources: [...ENVIRONMENTAL_RASTER_SOURCES, ...CLIMATE_RASTER_SOURCES],
  },
  administrative: {
    name: "Administratif",
    description: "Limites administratives",
    sources: ADMINISTRATIVE_VECTOR_SOURCES,
  },
  geology: {
    name: "Géologie",
    description: "Données géologiques et naturelles",
    sources: GEOLOGY_VECTOR_SOURCES,
  },
  infrastructure: {
    name: "Infrastructure",
    description: "Réseaux de transport",
    sources: INFRASTRUCTURE_VECTOR_SOURCES,
  },
  urban: {
    name: "Urbanisme",
    description: "Bâti et zones urbanisées",
    sources: URBAN_VECTOR_SOURCES,
  },
  soil: {
    name: "Sols et RUM",
    description: "Réserve utile maximale des sols et pédologie",
    sources: SOIL_WATER_CAPACITY_VECTOR_SOURCES,
  },
  demography: {
    name: "Démographie",
    description: "Population et villes",
    sources: DEMOGRAPHY_VECTOR_SOURCES,
  },
};
