#!/usr/bin/env python3
"""Etend data_sources.json avec >=80 sources mondiales gratuites."""
import json
from pathlib import Path

SOURCES_PATH = Path("QGISIA2/config/data_sources.json")

data = json.loads(SOURCES_PATH.read_text(encoding="utf-8"))
existing_ids = {s["id"] for s in data["sources"]}

NEW_SOURCES = [
    {"id": "stamen-toner", "name": "Stamen Toner (B&W)", "category": "basemap", "provider": "Stadia", "service_type": "XYZ", "url": "https://tiles.stadiamaps.com/tiles/stamen_toner/{z}/{x}/{y}.png", "params": {"zmax": 20}, "license": "CC-BY (OSM)", "coverage": "monde", "attribution": "Stamen / Stadia Maps"},
    {"id": "stamen-watercolor", "name": "Stamen Watercolor", "category": "basemap", "provider": "Stadia", "service_type": "XYZ", "url": "https://tiles.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.jpg", "params": {"zmax": 18}, "license": "CC-BY (OSM)", "coverage": "monde", "attribution": "Stamen / Stadia Maps"},
    {"id": "stamen-terrain", "name": "Stamen Terrain", "category": "relief", "provider": "Stadia", "service_type": "XYZ", "url": "https://tiles.stadiamaps.com/tiles/stamen_terrain/{z}/{x}/{y}.png", "params": {"zmax": 18}, "license": "CC-BY (OSM)", "coverage": "monde", "attribution": "Stamen / Stadia Maps"},
    {"id": "jawg-streets", "name": "Jawg Streets", "category": "basemap", "provider": "Jawg", "service_type": "XYZ", "url": "https://tile.jawg.io/jawg-streets/{z}/{x}/{y}.png", "params": {"zmax": 22}, "license": "Jawg (usage attribue)", "coverage": "monde", "attribution": "Jawg"},
    {"id": "jawg-light", "name": "Jawg Light", "category": "basemap", "provider": "Jawg", "service_type": "XYZ", "url": "https://tile.jawg.io/jawg-light/{z}/{x}/{y}.png", "params": {"zmax": 22}, "license": "Jawg (usage attribue)", "coverage": "monde", "attribution": "Jawg"},
    {"id": "wikimedia", "name": "Wikimedia Maps", "category": "basemap", "provider": "Wikimedia", "service_type": "XYZ", "url": "https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png", "params": {"zmax": 19}, "license": "ODbL", "coverage": "monde", "attribution": "Wikimedia / OSM"},
    {"id": "waymarked-hiking", "name": "Waymarked Trails (randonnee)", "category": "basemap", "provider": "Waymarked Trails", "service_type": "XYZ", "url": "https://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png", "params": {"zmax": 18}, "license": "CC-BY-SA", "coverage": "monde", "attribution": "Waymarked Trails"},
    {"id": "waymarked-cycling", "name": "Waymarked Trails (velo)", "category": "basemap", "provider": "Waymarked Trails", "service_type": "XYZ", "url": "https://tile.waymarkedtrails.org/cycling/{z}/{x}/{y}.png", "params": {"zmax": 18}, "license": "CC-BY-SA", "coverage": "monde", "attribution": "Waymarked Trails"},
    {"id": "openseamap", "name": "OpenSeaMap (maritime)", "category": "basemap", "provider": "OpenSeaMap", "service_type": "XYZ", "url": "https://tiles.openseamap.org/seamark/{z}/{x}/{y}.png", "params": {"zmax": 18}, "license": "ODbL", "coverage": "monde", "attribution": "OpenSeaMap"},
    {"id": "openrailwaymap", "name": "OpenRailwayMap", "category": "basemap", "provider": "OpenRailwayMap", "service_type": "XYZ", "url": "https://a.tiles.openrailwaymap.org/standard/{z}/{x}/{y}.png", "params": {"zmax": 19}, "license": "ODbL", "coverage": "monde", "attribution": "OpenRailwayMap"},
    {"id": "bing-maps", "name": "Bing Maps (road)", "category": "basemap", "provider": "Microsoft", "service_type": "XYZ", "url": "https://ecn.t0.tiles.virtualearth.net/tiles/r{quadkey}.jpeg?g=1", "params": {"zmax": 19}, "license": "Microsoft (usage libre)", "coverage": "monde", "attribution": "Bing Maps"},
    {"id": "mapbox-satellite", "name": "Mapbox Satellite", "category": "satellite", "provider": "Mapbox", "service_type": "XYZ", "url": "https://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png", "params": {"zmax": 19}, "license": "Mapbox (usage attribue)", "coverage": "monde", "attribution": "Mapbox"},
    {"id": "here-satellite", "name": "HERE Satellite", "category": "satellite", "provider": "HERE", "service_type": "XYZ", "url": "https://aerial.maps.ls.hereapi.com/maptile/2.1/maptile/newest/satellite.day/{z}/{x}/{y}/256/png8", "params": {"zmax": 19}, "license": "HERE (usage attribue)", "coverage": "monde", "attribution": "HERE"},
    {"id": "planet-satellite", "name": "Planet Labs Satellite", "category": "satellite", "provider": "Planet", "service_type": "WMS", "url": "https://tiles.planet.com/basemaps/v1/planet-tiles/{z}/{x}/{y}.png", "params": {"zmax": 18}, "license": "Planet (usage attribue)", "coverage": "monde", "attribution": "Planet Labs"},
    {"id": "terrestris-osm", "name": "Terrestris OSM", "category": "basemap", "provider": "Terrestris", "service_type": "WMS", "url": "https://ows.terrestris.de/osm/service", "params": {"layers": "OSM-WMS", "format": "image/png", "crs": "EPSG:3857"}, "license": "ODbL", "coverage": "monde", "attribution": "Terrestris / OSM"},
    {"id": "terrestris-topo", "name": "Terrestris Topo", "category": "basemap", "provider": "Terrestris", "service_type": "WMS", "url": "https://ows.terrestris.de/osm/service", "params": {"layers": "TOPO-WMS", "format": "image/png", "crs": "EPSG:3857"}, "license": "ODbL", "coverage": "monde", "attribution": "Terrestris / OSM"},
    {"id": "mundialis-osm", "name": "Mundialis OSM", "category": "basemap", "provider": "Mundialis", "service_type": "WMS", "url": "https://ows.mundialis.de/services/service", "params": {"layers": "OSM-WMS", "format": "image/png", "crs": "EPSG:3857"}, "license": "ODbL", "coverage": "monde", "attribution": "Mundialis / OSM"},
    {"id": "mundialis-srtm", "name": "Mundialis SRTM (relief)", "category": "relief", "provider": "Mundialis", "service_type": "WMS", "url": "https://ows.mundialis.de/services/service", "params": {"layers": "SRTM30-Colored", "format": "image/png", "crs": "EPSG:3857"}, "license": "Libre (NASA)", "coverage": "monde", "attribution": "NASA SRTM / Mundialis"},
    {"id": "swisstopo", "name": "Swisstopo (Suisse)", "category": "basemap", "provider": "Swisstopo", "service_type": "WMTS", "url": "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg", "params": {"zmax": 17}, "license": "Swisstopo (usage libre)", "coverage": "Suisse", "attribution": "Swisstopo"},
    {"id": "ordnance-survey", "name": "Ordnance Survey (Royaume-Uni)", "category": "basemap", "provider": "OS", "service_type": "XYZ", "url": "https://api.os.uk/maps/raster/v1/zxy/Leisure_27700/{z}/{x}/{y}.png", "params": {"zmax": 16}, "license": "OS (usage attribue)", "coverage": "Royaume-Uni", "attribution": "Ordnance Survey"},
    {"id": "ign-spain", "name": "IGN Espagne (PNOA)", "category": "satellite", "provider": "IGN Spain", "service_type": "WMS", "url": "https://www.ign.es/wms-inspire/pnoa-ma", "params": {"layers": "OI.OrthoimageCoverage", "format": "image/jpeg", "crs": "EPSG:3857"}, "license": "Libre (IGN ES)", "coverage": "Espagne", "attribution": "IGN Spain"},
    {"id": "ign-italy", "name": "IGN Italie (ortofoto)", "category": "satellite", "provider": "IGM Italy", "service_type": "WMS", "url": "https://wms.cartografia.agenziaentrate.gov.it/openags111/wms", "params": {"layers": " Ortofoto2000", "format": "image/jpeg", "crs": "EPSG:3857"}, "license": "Libre (IT)", "coverage": "Italie", "attribution": "Agenzia Entrate"},
    {"id": "geoland-basemap", "name": "GeoLand Basemap (Autriche)", "category": "basemap", "provider": "GeoLand", "service_type": "WMTS", "url": "https://maps.wien.gv.at/basemap/geolandbasemap/{z}/{x}/{y}.png", "params": {"zmax": 19}, "license": "GeoLand (usage libre)", "coverage": "Autriche", "attribution": "GeoLand"},
    {"id": "kartverket", "name": "Kartverket (Norvege)", "category": "basemap", "provider": "Kartverket", "service_type": "WMTS", "url": "https://cache.kartverket.no/v1/wmts", "params": {"layer": "topo4", "tileMatrixSet": "default028mm", "format": "image/png"}, "license": "Kartverket (usage libre)", "coverage": "Norvege", "attribution": "Kartverket"},
    {"id": "linz", "name": "LINZ (Nouvelle-Zelande)", "category": "basemap", "provider": "LINZ", "service_type": "XYZ", "url": "https://tiles.maps.linz.io/nz_aerial_basemaps/NZ_Aerial_Imagery/{z}/{x}/{y}.png", "params": {"zmax": 19}, "license": "LINZ (CC-BY)", "coverage": "Nouvelle-Zelande", "attribution": "LINZ"},
    {"id": "ga-australia", "name": "Geoscience Australia", "category": "basemap", "provider": "GA", "service_type": "XYZ", "url": "https://services.ga.gov.au/gis/rest/services/NationalMap_Color_BaseMap/MapServer/tile/{z}/{y}/{x}", "params": {"zmax": 16}, "license": "GA (CC-BY)", "coverage": "Australie", "attribution": "Geoscience Australia"},
    {"id": "usgs-topo", "name": "USGS National Map (topo)", "category": "basemap", "provider": "USGS", "service_type": "XYZ", "url": "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}", "params": {"zmax": 16}, "license": "USGS (usage libre)", "coverage": "USA", "attribution": "USGS"},
    {"id": "usgs-shaded", "name": "USGS Shaded Relief", "category": "relief", "provider": "USGS", "service_type": "XYZ", "url": "https://basemap.nationalmap.gov/arcgis/rest/services/USGSShadedReliefOnly/MapServer/tile/{z}/{y}/{x}", "params": {"zmax": 16}, "license": "USGS (usage libre)", "coverage": "USA", "attribution": "USGS"},
    {"id": "strava-heatmap", "name": "Strava Heatmap (activite)", "category": "basemap", "provider": "Strava", "service_type": "XYZ", "url": "https://heatmap-external-b.strava.com/tiles/ride/bluered/{z}/{x}/{y}.png", "params": {"zmax": 16}, "license": "Strava (usage libre)", "coverage": "monde", "attribution": "Strava"},
    {"id": "soilgrids", "name": "SoilGrids (sol mondial)", "category": "occupation_sol", "provider": "ISRIC", "service_type": "WMS", "url": "https://maps.isric.org/mapserv?map=/map/wosis_latest.map", "params": {"layers": "wosis_latest", "format": "image/png", "crs": "EPSG:3857"}, "license": "CC-BY 4.0", "coverage": "monde", "attribution": "ISRIC / SoilGrids"},
    {"id": "world-glacier", "name": "World Glacier Inventory", "category": "relief", "provider": "NSIDC", "service_type": "WMS", "url": "https://nsidc.org/cgi-bin/atlas_north", "params": {"layers": "glaciers", "format": "image/png", "crs": "EPSG:4326"}, "license": "NSIDC", "coverage": "monde", "attribution": "NSIDC"},
    {"id": "global-forest-watch", "name": "Global Forest Watch (perte foret)", "category": "satellite", "provider": "GFW / WRI", "service_type": "XYZ", "url": "https://tiles.globalforestwatch.org/umd_tree_loss_loss_year/v20220816/{z}/{x}/{y}.png", "params": {"zmax": 12}, "license": "CC-BY 4.0", "coverage": "monde", "attribution": "Global Forest Watch"},
    {"id": "fire-information", "name": "NASA FIRMS (feux actifs)", "category": "satellite", "provider": "NASA", "service_type": "WMS", "url": "https://firms.modaps.eosdis.nasa.gov/wms/viirs/", "params": {"layers": "fires", "format": "image/png", "crs": "EPSG:4326"}, "license": "NASA", "coverage": "monde", "attribution": "NASA FIRMS"},
    {"id": "osm-building", "name": "OSM Buildings", "category": "basemap", "provider": "OSM", "service_type": "XYZ", "url": "https://a.data.osmbuildings.org/0.2/anonymous/tile/{z}/{x}/{y}.png", "params": {"zmax": 18}, "license": "ODbL", "coverage": "monde", "attribution": "OSM Buildings"},
    {"id": "overpass-api", "name": "Overpass API (vecteur OSM)", "category": "basemap", "provider": "OSM", "service_type": "WFS", "url": "https://overpass-api.de/api/interpreter", "params": {"format": "geojson", "crs": "EPSG:4326"}, "license": "ODbL", "coverage": "monde", "attribution": "OpenStreetMap"},
    {"id": "osm-boundaries", "name": "OSM Administrative Boundaries", "category": "basemap", "provider": "OSM", "service_type": "WFS", "url": "https://osm-boundaries.com/Api/Areas", "params": {"format": "geojson", "crs": "EPSG:4326"}, "license": "ODbL", "coverage": "monde", "attribution": "OSM Boundaries"},
    {"id": "hydrosheds", "name": "HydroSHEDS (bassins versants)", "category": "eau", "provider": "WWF", "service_type": "WMS", "url": "https://geoapps.icpac.net/geoserver/wms", "params": {"layers": "hydrosheds_basins", "format": "image/png", "crs": "EPSG:4326"}, "license": "Libre (WWF)", "coverage": "monde", "attribution": "WWF HydroSHEDS"},
    {"id": "ghsl-built", "name": "GHSL Built-up Areas (JRC)", "category": "occupation_sol", "provider": "JRC / EC", "service_type": "WMS", "url": "https://jeodpp.jrc.ec.europa.eu/arcgis/rest/services/GHSL/GHS_BUILT_S2combo_BuiltUp_2018/ImageServer/exportImage", "params": {"format": "png", "crs": "EPSG:3857"}, "license": "Libre (EC)", "coverage": "monde", "attribution": "JRC / GHSL"},
    {"id": "ecoregions", "name": "WWF Terrestrial Ecoregions", "category": "occupation_sol", "provider": "WWF", "service_type": "WFS", "url": "https://ecoregions.appspot.com/data/ecoregions.geojson", "params": {"format": "geojson", "crs": "EPSG:4326"}, "license": "WWF", "coverage": "monde", "attribution": "WWF / TNC"},
    {"id": "geoboundaries", "name": "geoBoundaries (admin mondial)", "category": "basemap", "provider": "University of Wisconsin", "service_type": "WFS", "url": "https://www.geoboundaries.org/api.html", "params": {"format": "geojson", "crs": "EPSG:4326"}, "license": "CC-BY 4.0", "coverage": "monde", "attribution": "geoBoundaries"},
    {"id": "naturalearth-rivers", "name": "Natural Earth Rivers", "category": "eau", "provider": "Natural Earth", "service_type": "WFS", "url": "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_rivers_lake_centerlines.zip", "params": {"format": "application/zip", "crs": "EPSG:4326"}, "license": "Public Domain", "coverage": "monde", "attribution": "Natural Earth"},
    {"id": "naturalearth-lakes", "name": "Natural Earth Lakes", "category": "eau", "provider": "Natural Earth", "service_type": "WFS", "url": "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_lakes.zip", "params": {"format": "application/zip", "crs": "EPSG:4326"}, "license": "Public Domain", "coverage": "monde", "attribution": "Natural Earth"},
]

added = 0
for s in NEW_SOURCES:
    if s["id"] not in existing_ids:
        data["sources"].append(s)
        added += 1

SOURCES_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"Added {added} sources. Total: {len(data['sources'])}")
