#!/usr/bin/env python3
"""Etend symbology_presets.json avec >=40 presets institutionnels FR."""
import json
from pathlib import Path

PRESETS_PATH = Path("QGISIA2/config/symbology_presets.json")

data = json.loads(PRESETS_PATH.read_text(encoding="utf-8"))
existing_ids = {p["id"] for p in data["presets"]}

NEW_PRESETS = [
    {
        "id": "ens-espaces-naturels",
        "institution": "Environnement",
        "name": "Espaces naturels sensibles (ENS)",
        "geometry": "polygon",
        "field": "type_ens",
        "source": "Conseils departementaux / regions - ENS",
        "categories": [
            {"value": "ens_coastal", "label": "ENS littoral", "color": "#40E0D0"},
            {"value": "ens_forest", "label": "ENS forestier", "color": "#228B22"},
            {"value": "ens_wetland", "label": "ENS zone humide", "color": "#1E90FF"},
            {"value": "ens_mountain", "label": "ENS montagne", "color": "#808080"},
        ],
    },
    {
        "id": "parcs-nationaux",
        "institution": "Parcs nationaux",
        "name": "Coeurs et aires d'adhesion des parcs nationaux",
        "geometry": "polygon",
        "field": "zone",
        "source": "Parcs nationaux de France",
        "categories": [
            {"value": "coeur", "label": "Coeur de parc", "color": "#006400"},
            {"value": "aire_adhesion", "label": "Aire d'adhesion", "color": "#90EE90"},
            {"value": "aire_optimale", "label": "Aire optimale d'adhesion", "color": "#98FB98"},
        ],
    },
    {
        "id": "parcs-regionaux",
        "institution": "Parcs naturels regionaux",
        "name": "Parcs naturels regionaux (PNR)",
        "geometry": "polygon",
        "field": "statut",
        "source": "Federation des parcs naturels regionaux",
        "categories": [
            {"value": "pnr", "label": "Parc naturel regional", "color": "#556B2F"},
            {"value": "peripherie", "label": "Peripherie", "color": "#8FBC8F"},
        ],
    },
    {
        "id": "plu-sous-zones",
        "institution": "Urbanisme",
        "name": "PLU sous-zones detaillees (U/AU/A/N)",
        "geometry": "polygon",
        "field": "sous_zone",
        "source": "Code de l'urbanisme - zonage PLU detaille",
        "categories": [
            {"value": "U", "label": "Zone urbaine (U)", "color": "#EE8262"},
            {"value": "UA", "label": "U a", "color": "#FF6B6B"},
            {"value": "UB", "label": "U b", "color": "#FF8787"},
            {"value": "AU", "label": "A urbaniser (AU)", "color": "#FFA500"},
            {"value": "AUc", "label": "AU c", "color": "#FFB347"},
            {"value": "AUs", "label": "AU s", "color": "#FFCC80"},
            {"value": "A", "label": "Agricole (A)", "color": "#FFFF66"},
            {"value": "N", "label": "Naturelle (N)", "color": "#7CB342"},
            {"value": "ND", "label": "N d", "color": "#8BC34A"},
        ],
    },
    {
        "id": "plui",
        "institution": "Urbanisme",
        "name": "PLUi (intercommunal)",
        "geometry": "polygon",
        "field": "zonage",
        "source": "Code de l'urbanisme - PLUi",
        "categories": [
            {"value": "U", "label": "Urbain", "color": "#EE8262"},
            {"value": "AU", "label": "A urbaniser", "color": "#FFA500"},
            {"value": "A", "label": "Agricole", "color": "#FFFF66"},
            {"value": "N", "label": "Naturel", "color": "#7CB342"},
        ],
    },
    {
        "id": "scot",
        "institution": "Urbanisme",
        "name": "SCOT (schema de coherence territoriale)",
        "geometry": "polygon",
        "field": "orientation",
        "source": "Code de l'urbanisme - SCOT",
        "categories": [
            {"value": "urbanise", "label": "A urbaniser", "color": "#FF6B6B"},
            {"value": "a_structurer", "label": "A structurer", "color": "#FFB347"},
            {"value": "a_preserver", "label": "A preserver", "color": "#7CB342"},
            {"value": "naturel", "label": "Naturel", "color": "#228B22"},
        ],
    },
    {
        "id": "servitudes",
        "institution": "Urbanisme",
        "name": "Servitudes d'utilite publique",
        "geometry": "polygon",
        "field": "type_servitude",
        "source": "Servitudes d'utilite publique",
        "categories": [
            {"value": "ligne_ht", "label": "Ligne HT", "color": "#FF0000"},
            {"value": "gaz", "label": "Canalisation gaz", "color": "#FFD700"},
            {"value": "eau", "label": "Conduite eau", "color": "#0000FF"},
            {"value": "easement", "label": "Autre servitude", "color": "#808080"},
        ],
    },
    {
        "id": "oap",
        "institution": "Urbanisme",
        "name": "OAP (orientation amenagement programmation)",
        "geometry": "polygon",
        "field": "type_oap",
        "source": "PLU - OAP",
        "categories": [
            {"value": "renouvellement_urbain", "label": "Renouvellement urbain", "color": "#FF6B6B"},
            {"value": "extension", "label": "Extension", "color": "#FFA500"},
            {"value": "sequencage", "label": "Sequencage", "color": "#87CEEB"},
        ],
    },
    {
        "id": "emplacements-reserves",
        "institution": "Urbanisme",
        "name": "Emplacements reserves",
        "geometry": "polygon",
        "field": "type_emplacement",
        "source": "PLU - emplacements reserves",
        "categories": [
            {"value": "equipement", "label": "Equipement public", "color": "#9370DB"},
            {"value": "voirie", "label": "Voirie", "color": "#A9A9A9"},
            {"value": "vert", "label": "Espace vert", "color": "#32CD32"},
        ],
    },
    {
        "id": "zac",
        "institution": "Urbanisme",
        "name": "ZAC (zone d'aménagement concerte)",
        "geometry": "polygon",
        "field": "phase",
        "source": "ZAC - phases d'aménagement",
        "categories": [
            {"value": "creation", "label": "Creation", "color": "#FF6347"},
            {"value": "amenagement", "label": "Aménagement", "color": "#FFA500"},
            {"value": "realisation", "label": "Realisation", "color": "#32CD32"},
            {"value": "achevee", "label": "Achevee", "color": "#228B22"},
        ],
    },
    {
        "id": "dup",
        "institution": "Urbanisme",
        "name": "DUP / DPU (declaration d'utilite publique)",
        "geometry": "polygon",
        "field": "nature",
        "source": "DUP/DPU",
        "categories": [
            {"value": "voirie", "label": "Voirie", "color": "#808080"},
            {"value": "infrastructure", "label": "Infrastructure", "color": "#FF4500"},
            {"value": "equipement", "label": "Equipement", "color": "#4169E1"},
        ],
    },
    {
        "id": "pprn-feu",
        "institution": "Risques (PPRn)",
        "name": "PPRn feu de foret",
        "geometry": "polygon",
        "field": "alea",
        "source": "PPRn - feu de foret",
        "categories": [
            {"value": "fort", "label": "Alea fort", "color": "#E31A1C"},
            {"value": "moyen", "label": "Alea moyen", "color": "#FD8D3C"},
            {"value": "faible", "label": "Alea faible", "color": "#FECC5C"},
            {"value": "residuel", "label": "Alea residuel", "color": "#FFFFCC"},
        ],
    },
    {
        "id": "pprn-avalanche",
        "institution": "Risques (PPRn)",
        "name": "PPRn avalanche",
        "geometry": "polygon",
        "field": "alea",
        "source": "PPRn - avalanche",
        "categories": [
            {"value": "rouge", "label": "Zone rouge", "color": "#E31A1C"},
            {"value": "bleu", "label": "Zone bleue", "color": "#1F78B4"},
            {"value": "blanc", "label": "Zone blanche", "color": "#F0F0F0"},
        ],
    },
    {
        "id": "pprt",
        "institution": "Risques (PPRT)",
        "name": "PPRT (plan de prevention risques technologiques)",
        "geometry": "polygon",
        "field": "zone",
        "source": "PPRT - zones",
        "categories": [
            {"value": "icpe", "label": "ICPE", "color": "#FF0000"},
            {"value": "transport", "label": "Transport matieres dangereuses", "color": "#FF4500"},
            {"value": "nuisible", "label": "Etablissement nuisible", "color": "#FFA500"},
        ],
    },
    {
        "id": "tri-inondation",
        "institution": "Risques (TRI)",
        "name": "TRI (territoires a risque importants d'inondation)",
        "geometry": "polygon",
        "field": "niveau_risque",
        "source": "TRI - zonage inondation",
        "categories": [
            {"value": "tres_eleve", "label": "Tres eleve", "color": "#8B0000"},
            {"value": "eleve", "label": "Eleve", "color": "#FF0000"},
            {"value": "moyen", "label": "Moyen", "color": "#FFA500"},
            {"value": "faible", "label": "Faible", "color": "#FFFF00"},
        ],
    },
    {
        "id": "retrait-gonflement",
        "institution": "Risques",
        "name": "Aleas retrait-gonflement des argiles",
        "geometry": "polygon",
        "field": "alea",
        "source": "BRGM - aleas argiles",
        "categories": [
            {"value": "fort", "label": "Alea fort", "color": "#E31A1C"},
            {"value": "moyen", "label": "Alea moyen", "color": "#FD8D3C"},
            {"value": "faible", "label": "Alea faible", "color": "#FECC5C"},
            {"value": "nul", "label": "Alea nul", "color": "#90EE90"},
        ],
    },
    {
        "id": "sismicite",
        "institution": "Risques",
        "name": "Sismicite (zones de sismcite)",
        "geometry": "polygon",
        "field": "zone",
        "source": "Plan de prevention des risques sismiques",
        "categories": [
            {"value": "1_faible", "label": "Zone 1 - Faible", "color": "#90EE90"},
            {"value": "2_moyen", "label": "Zone 2 - Moyen", "color": "#FFD700"},
            {"value": "3_modere", "label": "Zone 3 - Modere", "color": "#FFA500"},
            {"value": "4_fort", "label": "Zone 4 - Fort", "color": "#FF4500"},
            {"value": "5_tres_fort", "label": "Zone 5 - Tres fort", "color": "#E31A1C"},
        ],
    },
    {
        "id": "bd-charm",
        "institution": "Sol",
        "name": "BD Charm (contamination sols)",
        "geometry": "polygon",
        "field": "niveau",
        "source": "ADEME - BD Charm",
        "categories": [
            {"value": "sensible", "label": "Zone sensible", "color": "#FF6347"},
            {"value": "potentiellement_affecte", "label": "Potentiellement affecte", "color": "#FFA500"},
            {"value": "non_affecte", "label": "Non affecte", "color": "#90EE90"},
        ],
    },
    {
        "id": "hydrogeologie",
        "institution": "BRGM",
        "name": "Hydrogeologie (nappes)",
        "geometry": "polygon",
        "field": "type_nappe",
        "source": "BRGM - hydrogeologie",
        "categories": [
            {"value": "alluviale", "label": "Nappe alluviale", "color": "#1E90FF"},
            {"value": "chalk", "label": "Nappe de craie", "color": "#87CEEB"},
            {"value": "karstique", "label": "Karst", "color": "#4682B4"},
            {"value": "libre", "label": "Nappe libre", "color": "#00BFFF"},
            {"value": "captive", "label": "Nappe captive", "color": "#000080"},
        ],
    },
    {
        "id": "rum",
        "institution": "Sol",
        "name": "RUM (referentiel usage des sols)",
        "geometry": "polygon",
        "field": "usage",
        "source": "CESBIO - RUM",
        "categories": [
            {"value": "agricole", "label": "Agricole", "color": "#F5DEB3"},
            {"value": "forestier", "label": "Forestier", "color": "#228B22"},
            {"value": "urbain", "label": "Urbain", "color": "#A9A9A9"},
            {"value": "eau", "label": "Eau", "color": "#1E90FF"},
            {"value": "naturel", "label": "Naturel", "color": "#8FBC8F"},
        ],
    },
    {
        "id": "clc-niveau2",
        "institution": "Corine Land Cover",
        "name": "Occupation du sol CLC niveau 2",
        "geometry": "polygon",
        "field": "clc2",
        "source": "Corine Land Cover niveau 2",
        "categories": [
            {"value": "111", "label": "Tissu urbain continu", "color": "#E6004D"},
            {"value": "112", "label": "Tissu urbain discontinu", "color": "#FF1A8C"},
            {"value": "211", "label": "Terres arables hors irrigation", "color": "#FFFFA8"},
            {"value": "231", "label": "Prairies", "color": "#E6E64D"},
            {"value": "311", "label": "Forets de feuillus", "color": "#80FF00"},
            {"value": "312", "label": "Forets de coniferes", "color": "#00A600"},
            {"value": "313", "label": "Forets melangees", "color": "#A6FF80"},
            {"value": "321", "label": "Pelouses et landes", "color": "#A6A64D"},
        ],
    },
    {
        "id": "clc-niveau3",
        "institution": "Corine Land Cover",
        "name": "Occupation du sol CLC niveau 3",
        "geometry": "polygon",
        "field": "clc3",
        "source": "Corine Land Cover niveau 3 (exemples)",
        "categories": [
            {"value": "111", "label": "Tissu urbain continu", "color": "#E6004D"},
            {"value": "112", "label": "Tissu urbain discontinu", "color": "#FF1A8C"},
            {"value": "121", "label": "Industrie et commerce", "color": "#FF66B3"},
            {"value": "122", "label": "Reseaux routiers et assimilés", "color": "#FFB3D9"},
            {"value": "211", "label": "Terres arables hors irrigation", "color": "#FFFFA8"},
            {"value": "221", "label": "Vignobles", "color": "#E6CC00"},
            {"value": "231", "label": "Prairies", "color": "#E6E64D"},
        ],
    },
    {
        "id": "masses-eau",
        "institution": "Eau",
        "name": "Masses d'eau (DCE)",
        "geometry": "polygon",
        "field": "type_masse",
        "source": "DCE - masses d'eau",
        "categories": [
            {"value": "cours_eau", "label": "Cours d'eau", "color": "#1E90FF"},
            {"value": "plan_eau", "label": "Plan d'eau", "color": "#4682B4"},
            {"value": "eau_souterraine", "label": "Eau souterraine", "color": "#000080"},
            {"value": "estuaire", "label": "Estuaire", "color": "#5F9EA0"},
            {"value": "cote", "label": "Eaux cotieres", "color": "#00CED1"},
        ],
    },
    {
        "id": "zones-humides",
        "institution": "Environnement",
        "name": "Zones humides",
        "geometry": "polygon",
        "field": "type_z_humide",
        "source": "INPN - zones humides",
        "categories": [
            {"value": "mare", "label": "Mare", "color": "#4682B4"},
            {"value": "marais", "label": "Marais", "color": "#5F9EA0"},
            {"value": "tourbiere", "label": "Tourbiere", "color": "#8B4513"},
            {"value": "estuaire", "label": "Estuaire", "color": "#2E8B57"},
            {"value": "mangrove", "label": "Mangrove", "color": "#006400"},
        ],
    },
    {
        "id": "bassins-versants",
        "institution": "Eau",
        "name": "Bassins versants / sous-bassins",
        "geometry": "polygon",
        "field": "echelle",
        "source": "Sandre - bassins versants",
        "categories": [
            {"value": "grand", "label": "Grand bassin", "color": "#0000CD"},
            {"value": "moyen", "label": "Bassin moyen", "color": "#4169E1"},
            {"value": "petit", "label": "Petit bassin", "color": "#87CEEB"},
        ],
    },
    {
        "id": "sage",
        "institution": "Eau",
        "name": "SAGE (schemas d'amenagement et de gestion des eaux)",
        "geometry": "polygon",
        "field": "statut",
        "source": "SAGE - statut",
        "categories": [
            {"value": "approuve", "label": "Approuve", "color": "#228B22"},
            {"value": "elaboration", "label": "En elaboration", "color": "#FFD700"},
            {"value": "revision", "label": "En revision", "color": "#FFA500"},
        ],
    },
    {
        "id": "pcrs",
        "institution": "Cadastre",
        "name": "PCRS (plan corps de rue simplifie)",
        "geometry": "polygon",
        "field": "type_objet",
        "source": "DGFiP - PCRS",
        "categories": [
            {"value": "batiment", "label": "Batiment", "color": "#D9B38C"},
            {"value": "parcelle", "label": "Parcelle", "color": "#FBE9D0"},
            {"value": "voirie", "label": "Voirie", "color": "#A9A9A9"},
            {"value": "signalisation", "label": "Signalisation", "color": "#FF4500"},
        ],
    },
    {
        "id": "reseaux-electricite",
        "institution": "Reseaux",
        "name": "Reseaux electriques",
        "geometry": "line",
        "field": "tension",
        "source": "Reseaux electriques",
        "categories": [
            {"value": "ht", "label": "Haute tension", "color": "#FF0000"},
            {"value": "mt", "label": "Moyenne tension", "color": "#FFA500"},
            {"value": "bt", "label": "Basse tension", "color": "#0000FF"},
            {"value": "souterrain", "label": "Souterrain", "color": "#808080"},
        ],
    },
    {
        "id": "reseaux-gaz",
        "institution": "Reseaux",
        "name": "Reseaux gaz",
        "geometry": "line",
        "field": "pression",
        "source": "Reseaux gaz",
        "categories": [
            {"value": "haute", "label": "Haute pression", "color": "#FFD700"},
            {"value": "moyenne", "label": "Moyenne pression", "color": "#FFA500"},
            {"value": "basse", "label": "Basse pression", "color": "#32CD32"},
        ],
    },
    {
        "id": "reseaux-telecom",
        "institution": "Reseaux",
        "name": "Reseaux telecom / fibre optique",
        "geometry": "line",
        "field": "type_reseau",
        "source": "Reseaux telecom",
        "categories": [
            {"value": "fibre", "label": "Fibre optique", "color": "#00CED1"},
            {"value": "cuivre", "label": "Cuivre", "color": "#B87333"},
            {"value": "coaxial", "label": "Coaxial", "color": "#A9A9A9"},
        ],
    },
    {
        "id": "aoc-aop",
        "institution": "Agriculture",
        "name": "AOC / AOP (appellations)",
        "geometry": "polygon",
        "field": "appellation",
        "source": "INAO - AOC/AOP",
        "categories": [
            {"value": "aoc", "label": "AOC", "color": "#800080"},
            {"value": "aop", "label": "AOP", "color": "#9370DB"},
            {"value": "igp", "label": "IGP", "color": "#BA55D3"},
            {"value": "stg", "label": "STG", "color": "#DDA0DD"},
        ],
    },
    {
        "id": "prairies",
        "institution": "Agriculture",
        "name": "Prairies permanentes",
        "geometry": "polygon",
        "field": "type_prairie",
        "source": "RPG - prairies",
        "categories": [
            {"value": "permanente", "label": "Prairie permanente", "color": "#7CFC00"},
            {"value": "temporaire", "label": "Prairie temporaire", "color": "#ADFF2F"},
            {"value": "montagne", "label": "Prairie de montagne", "color": "#6B8E23"},
        ],
    },
    {
        "id": "zones-enr",
        "institution": "Energie",
        "name": "Zones ENR (energies renouvelables)",
        "geometry": "polygon",
        "field": "type_enr",
        "source": "Zones potentielles ENR",
        "categories": [
            {"value": "eolien", "label": "Eolien", "color": "#00BFFF"},
            {"value": "solaire", "label": "Solaire", "color": "#FFD700"},
            {"value": "hydro", "label": "Hydraulique", "color": "#1E90FF"},
            {"value": "biomasse", "label": "Biomasse", "color": "#228B22"},
        ],
    },
    {
        "id": "qualite-air-atmo",
        "institution": "ATMO",
        "name": "Qualite de l'air (ATMO)",
        "geometry": "polygon",
        "field": "indice",
        "source": "ATMO - indices qualite air",
        "categories": [
            {"value": "1", "label": "Tres bon", "color": "#50F0E6"},
            {"value": "2", "label": "Bon", "color": "#50CCAA"},
            {"value": "3", "label": "Moyen", "color": "#F0E641"},
            {"value": "4", "label": "Degrade", "color": "#FF5050"},
            {"value": "5", "label": "Mauvais", "color": "#960050"},
            {"value": "6", "label": "Tres mauvais", "color": "#7D2181"},
        ],
    },
    {
        "id": "bruit-strategique",
        "institution": "Bruit",
        "name": "Cartes strategiques de bruit",
        "geometry": "polygon",
        "field": "lden",
        "source": "Plans de prevention du bruit",
        "categories": [
            {"value": "55_59", "label": "55-59 dB", "color": "#90EE90"},
            {"value": "60_64", "label": "60-64 dB", "color": "#FFD700"},
            {"value": "65_69", "label": "65-69 dB", "color": "#FFA500"},
            {"value": "70_74", "label": "70-74 dB", "color": "#FF6347"},
            {"value": "75_plus", "label": "> 75 dB", "color": "#E31A1C"},
        ],
    },
]

added = 0
for p in NEW_PRESETS:
    if p["id"] not in existing_ids:
        data["presets"].append(p)
        added += 1

PRESETS_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"Added {added} presets. Total: {len(data['presets'])}")
